name: pvzmdz_editor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.12.0
  logger: ^2.7.0
  path_provider: ^2.1.5
  shizuku_api: ^1.2.2
  win32: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
