name: 🛠 Build & Release

on:
  push:
    branches: [main, master]
    paths:
      - /assets/**/*
      - /lib/**/*.dart
      - /pubspec.yaml
      - /pubspec.lock
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  windows:
    uses: ./.github/workflows/windows.yaml

  android:
    uses: ./.github/workflows/android.yaml
