name: 🛠 Windows CI / Build & Release EXE

on:
  workflow_call:

permissions:
  contents: write # allow creating/updating Releases & uploading assets
  actions: read # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v6

      - name: 🚀 Cache pub deps
        uses: actions/cache@v5
        with:
          path: ~/AppData/Local/Pub/Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 📥 Get dependencies
        run: flutter pub get

      - name: 🚧 Codegen
        run: dart run build_runner build

      - name: 🏗️ Build EXE
        run: flutter build windows --release

      - name: 📦 Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          cp build/windows/x64/runner/Release/*.exe artifacts/
          cp build/windows/x64/runner/Release/*.dll artifacts/
          cp -r build/windows/x64/runner/Release/data artifacts/

      - name: 🐞 Upload to action artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-x86_64
          path: artifacts/*
          retention-days: 90

      # ─────────────── ONLY ON TAGS ───────────────
      - name: 🏷️ Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: artifacts.zip
